name: Build

on: [ push, pull_request ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android build environment
        uses: android-actions/setup-android@v2
      - name: Build whole project with gradle
        run: ./gradlew build
      - name: Distribute Desktop
        run: ./gradlew desktop:dist
      - name: Distribute Android
        run: ./gradlew android:assembleRelease
      - name: Distribute HTML
        run: ./gradlew html:dist
      - name: Upload dists
        uses: actions/upload-artifact@v2.1.4
        with:
          name: desktop
          path: desktop/build/libs/*
      - name: Upload dists
        uses: actions/upload-artifact@v2.1.4
        with:
          name: android
          path: android/build/outputs/apk/android-release-unsigned.apk
      - name: Upload dists
        uses: actions/upload-artifact@v2.1.4
        with:
          name: html
          path: html/build/dist/
